<a href="https://colab.research.google.com/github/irynechess/P_and_K_online_stores/blob/main/CLASSIFICATION.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas
data = pandas.read_csv('https://modcom.co.ke/data/datasets/pima.csv')
data
# 1 -Positive
#0 - Negative
#ML RULES
#Rule 1: you cannot have empties
#Rule 2: X - features cannot be strings - leters, the must be numbers
# i.e a column with countries eg Arizona, kenya, encode them to 0- kenya,  1- uganda

     Pregnancies  Glucose  ...  Age  Outcome
0              6      148  ...   50        1
1              1       85  ...   31        0
2              8      183  ...   32        1
3              1       89  ...   21        0
4              0      137  ...   33        1
..           ...      ...  ...  ...      ...
763           10      101  ...   63        0
764            2      122  ...   27        0
765            5      121  ...   30        0
766            1      126  ...   47        1
767            1       93  ...   23        0

[768 rows x 9 columns]

In [ ]:
# Assume there are not empties
data['Outcome'].fillna(2, inplace=True)


#Classification
array = data.values
X= array[:,0:8]#  4 is not counted, there is only a -1
Y= array[:, 8]
# NB above X,Y has all rows

#nb above x, Y has all rows
from sklearn import model_selection #spliting features
X_train, X_test, Y_train, Y_Test = model_selection.train_test_split(X,Y, test_size=0.30,
                                                                   random_state=42)


#import algorithms
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

#https://justpaste.it/5vsd4
# Spot Check Algorithms
models = []
models.append(('LR', LogisticRegression(solver='liblinear', multi_class='ovr')))
models.append(('LDA', LinearDiscriminantAnalysis()))
models.append(('KNN', KNeighborsClassifier()))
models.append(('CART', DecisionTreeClassifier()))
models.append(('NB', GaussianNB()))
models.append(('SVM', SVC(gamma='auto')))
models.append(('RF', RandomForestClassifier()))
models.append(('GBC', GradientBoostingClassifier()))
# evaluate each model in turn

for name, model in models:
      kfold = model_selection.KFold(n_splits=10, random_state=42, shuffle=True)
      cv_results = model_selection.cross_val_score(model, X_train, Y_train, cv=kfold, scoring='accuracy')
      print(name, cv_results.mean())

LR 0.7654437456324248
LDA 0.7729559748427673
KNN 0.7208944793850453
CART 0.7300838574423479
NB 0.7507686932215234
SVM 0.6498602375960866
RF 0.7617051013277429
GBC 0.7728162124388539

In [ ]:
#create a model
model= LogisticRegression(solver='liblinear', multi_class='ovr')
model.fit(X_train, Y_train)

# ask the model to predict the X_test as you hide the Y_test
predictions = model.predict(X_test)
#print('Model Predictions', predictions)
#print('Expected', Y_Test)


from sklearn.metrics import accuracy_score
print('Model accuracy', accuracy_score(Y_Test,predictions))


from sklearn.metrics import  classification_report
print(classification_report(Y_Test, predictions))

from sklearn.metrics import confusion_matrix
print(confusion_matrix(Y_Test, predictions))



# class imbalance Problem
# Solution- add more data to the positives
# Create artificial data -read on SMOTE

newpatient = [[2, 93,70,31,0, 30.4, 0.315, 40]]
predicted = model.predict(newpatient)
print('predicted @76% CL', predicted)

Model accuracy 0.7619047619047619
              precision    recall  f1-score   support

         0.0       0.81      0.83      0.82       151
         1.0       0.67      0.62      0.65        80

    accuracy                           0.76       231
   macro avg       0.74      0.73      0.73       231
weighted avg       0.76      0.76      0.76       231

[[126  25]
 [ 30  50]]
predicted @76% CL [0.]